### ISSUE TITLE
addPoliciesFromPath() should custom descriptions rather than file path

### ISSUE THREAD

**Issue by ncino-esselman** [cdklabs/cdk-verified-permissions#196]
Currently if you lever `addPoliciesFromPath()` from the Policy store the description on each policy is defaulted to the absolute file path. This is ugly and also opens up information about the system that deploys the policies.

Possibly a cedar annotation in the policy itself or even just the file name instead of the path might be better

**Comment by reste85** [comment]
Thanks @ncino-esselman, taking a look

**Comment by ncino-esselman** [comment]
Thanks. There are a few options and I might try exploring targeting a comments annotation in the file but honestly the easiest would just be the file name minus the extension instead of the full path. Happy to contribute as well if that works

**Comment by reste85** [comment]
@ncino-esselman i've implemented a fix (https://github.com/cdklabs/cdk-verified-permissions/pull/202) for using the relative path instead of the absolute one. I would keep also the file extension, it brings more clarity. Meantime i'm working also on a possible annotation, but here i would like to spend some more time... i'll open a draft PR in few moments and then continue on it in the following days

**Comment by reste85** [comment]
This is the draft pr i'm working on https://github.com/cdklabs/cdk-verified-permissions/pull/203 to add the annotation to specify the description of the policy

**Comment by ncino-esselman** [comment]
Awesome! Thank you so much

**Comment by reste85** [comment]
@ncino-esselman  we released also 0.1.1 version which contains an annotation to specify description of policy. 
See https://github.com/cdklabs/cdk-verified-permissions/pull/203

**Comment by ncino-esselman** [comment]
A+ !! Thank you
