### ISSUE TITLE
proposal: schemaFromRestApi Method

### ISSUE THREAD

**Issue by joshkraft** [cdklabs/cdk-verified-permissions#220]
Hi team,

It would be great to be able to generate a schema based off of CloudFormation templates, rather than having to deploy the API, export a swagger spec, and then generate based off of that.

What do you think of a new method `schemaFromCloudFormationTemplate()`?. I am thinking it would work exactly like `schemaFromOpenApiSpec()`, just with a different source. 

If this aligns with the project’s direction, I’d be happy to make a contribution.

**Comment by andreameroni** [comment]
Hi @joshkraft, thanks for your proposal and your contribution!

Let me discuss it with the team and come back to you

**Comment by andreameroni** [comment]
Hi @joshkraft,

We discussed your proposal internally and would like to hear more about your use case, specifically about the need to generate a schema from a CloudFormation template

Rather than parsing the template and generate a schema, which would imply several assumptions (e.g. no more than 1 API per template), we suggest to implement a functionality that generates the schema from another CDK construct e.g. [Rest API](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.RestApi.html)

Also, for users that want/need to start from a CloudFormation template the suggested way would be to [import it in CDK](https://docs.aws.amazon.com/cdk/v2/guide/use_cfn_template.html)

What do you think?

**Comment by joshkraft** [comment]
Hi Andrea - thanks for the response. I think working with the RestApi construct would work for our use case. Would you be open to a contribution that adds something like schemaFromRestApi to this project?
